"""05_refresh_token_user_unique_constraint

Revision ID: 58870b114124
Revises: 79faca7abbc5
Create Date: 2024-05-01 17:37:32.712312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58870b114124'
down_revision: Union[str, None] = '79faca7abbc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_id', 'refresh_token', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_id', 'refresh_token', type_='unique')
    # ### end Alembic commands ###
