"""04_refresh_token_user_unique

Revision ID: 79faca7abbc5
Revises: da045ddf9159
Create Date: 2024-05-01 13:03:06.177067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79faca7abbc5'
down_revision: Union[str, None] = 'da045ddf9159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_token_id', table_name='refresh_token')
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.create_index('ix_refresh_token_id', 'refresh_token', ['id'], unique=False)
    # ### end Alembic commands ###
