version: '3.3'
services:
  database:
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - "5432:5432"
    restart:
      always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: 'bitnami/minio:latest'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    volumes:
      - ./:/minio/data

#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    env_file:
#      - ./backend/.env
#    volumes:
#      - ./backend/src:/app/src
#    ports:
#      - "8000:3000"
#    command: sh -c "yarn && yarn build && npx typeorm migration:run && yarn start:dev"
#    depends_on:
#      - db

  backend:
    build:
      context: ./backend_fastapi
      dockerfile: Dockerfile
    env_file:
      - ./backend_fastapi/.env
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend_fastapi/alembic:/app/alembic
      - ./backend_fastapi/src:/app/src

  redis:
    image: redis:6.2.6
    command: redis-server --requirepass ${REDIS_PASSWORD:-secret}
    ports:
      - "6379:6379"
  adminer:
    image: adminer
    ports:
      - "8080:8080"
#  client:
#    build:
#      context: ./client
#      dockerfile: Dockerfile
#    env_file:
#      - ./client/.env
#    volumes:
#      - ./client:/app
#    ports:
#      - "3000:3000"

volumes:
  postgres_data: